apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: redash
  name: redash-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redash-role-binding
  namespace: redash
subjects:
  - kind: ServiceAccount
    name: redash-sa
    namespace: redash
roleRef:
  kind: Role
  name: redash-role
  apiGroup: rbac.authorization.k8s.io